application: greater-or-less
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: got.app

libraries:
- name: jinja2
  version: latest
- name: webob
  version: latest
- name: pycrypto
  version: latest

